# https://pub.dev/packages/pedantic_mono
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    prefer_single_quotes: true


analyzer:
  strong-mode:
    # Freezed がうまく動かないため.
    implicit-dynamic: true
  exclude:
    #    - "lib/ui/route/*"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"